spring:
  profiles:
    active: dev  # 또는 prod 로 바꿔가며 사용

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

app:
  jwtRefreshExpirationMs: 604800000

openapi:
  1365:
    secret: kktz5VWig27i6B0yiEAKhnpA%2F1s0ZJHD1sTIZDFzpr%2BH%2Bu8QMHKP%2BLTd7Loev4zHSDktWB5cC0xnTM3FAbV7SA%3D%3D

kakao:
  client-id: a1b1677f84f92240f21d384d5517c525
  redirect-uri: "http://localhost:8080/api/kakao/token"

blockchain:
  rpc-url: https://eth-sepolia.g.alchemy.com/v2/ZSHRWWYeydgV-uBQDS8EhdLiSa7c4g7p
  private-key: 5f5804b6df2829e7938d0b795e8978370907abd7085635cd4b45ff945073f678
