spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/uniton}
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

app:
  jwtRefreshExpirationMs: 604800000

openapi:
  1365:
    secret: kktz5VWig27i6B0yiEAKhnpA%2F1s0ZJHD1sTIZDFzpr%2BH%2Bu8QMHKP%2BLTd7Loev4zHSDktWB5cC0xnTM3FAbV7SA%3D%3D

kakao:
  client-id: a1b1677f84f92240f21d384d5517c525
  redirect-uri: "http://localhost:8080/api/kakao/token"